---
- hosts: all
  tasks:
  
  - name: Detener WCOMPENSAR
    win_iis_webapppool:
      name: WCOMPENSAR
      state: stopped

  - name: Detener WCONSULTAS
    win_iis_webapppool:
      name: WCONSULTAS
      state: stopped
