---
- hosts: all
  tasks:
  
  - name: stop an application pool
    win_iis_webapppool:
      name: WCOMPENSAR
      state: started

  - name: stop an application pool
    win_iis_webapppool:
      name: WCONSULTAS
      state: started